# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (-1, '-1'), (-1, '-1'), (-2, '-2'), (-3, '-3'), (-4, '-4'), (-5, '-5'), (-6, '-6'), (-7, '-7'), (-8, '-8'), (-9, '-9'), (-10, '-10')]),
        ),
    ]
